# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM python:3.11-slim

# Ensure output is unbuffered
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install FastMCP
RUN pip install --no-cache-dir fastmcp

# Copy application code
COPY pearch_mcp.py .

# Default command to run the MCP server
CMD ["python", "pearch_mcp.py"]
